#/bin/bash

cp resource_sematext_monitor_infra.go resource_sematext_monitor_docker.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_solr.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_solrcloud.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_elasticsearch.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_akka.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_java.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_tomcat.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_zookeeper.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_kafka.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_clickhouse.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_aws.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_cassandra.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_nginx.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_nginxplus.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_mongodb.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_nodejs.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_apache.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_mysql.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_hbase.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_redis.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_storm.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_haproxy.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_spark.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_yarn.go
cp resource_sematext_monitor_infra.go resource_sematext_monitor_hadoop.go
cp resource_sematext_monitor_infra.go resource_sematext_logging_sink.go


cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_docker_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_solr_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_solrcloud_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_elasticsearch_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_akka_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_java_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_tomcat_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_zookeeper_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_kafka_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_clickhouse_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_aws_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_cassandra_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_nginx_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_nginxplus_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_mongodb_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_nodejs_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_apache_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_mysql_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_hbase_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_redis_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_storm_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_haproxy_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_spark_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_yarn_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_monitor_hadoop_test.go
cp resource_sematext_monitor_infra_test.go resource_sematext_logging_sink_test.go




